name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install and Build 🔧
      env:
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install -g mermaid.cli
        bundle exec jekyll build
    - name: Deploy 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
      with:
        folder: _site
